version: "3"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask-app:
    build:
      context: ./customers_api
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  react-app:
    build:
      context: ./customerspage
    ports:
      - "3000:3000"
    depends_on:
      - flask-app

volumes:
  mysql_data:
